name: Daily Schedule

on:
  schedule:
    - cron: '13 15 * * *'  # Runs every day at 10 AM SGT (2 AM UTC)

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace '3.x' with your desired Python version

    - name: Run Python script
      run: python dailySchedule.py  # Replace 'dailySchedule.py' with the name of your Python script

    - name: List Files in Current Directory
      run: ls  # Use the 'ls' command to list files in the CWD
